### ISSUE TITLE
/lib/db not found

### ISSUE THREAD

**Issue by ragnarok22** [RoylerMarichal/multipurpose-boilerplate-full-stack-in-next#1]
![image](https://github.com/RoylerMarichal/multipurpose-boilerplate-full-stack-in-next/assets/8838803/88c821da-d5ad-4bd1-9c07-d00383b593db)

**Comment by RoylerMarichal** [comment]
Thanks for noticing, I was ignoring the file that optimizes prism loading. I already added it.
